/* CREATE TABLE */
CREATE TABLE `users`(
`id` BIGINT(255) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
`fname` VARCHAR(255) NOT NULL, 
`lname` VARCHAR(255) NOT NULL, 
`email` VARCHAR(255) NOT NULL UNIQUE, 
`password` VARCHAR(345) NOT NULL,
`date_created` VARCHAR(255)
);